Task1

1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [5]:
def comp(x,y):
    try:
        div = x/y
        print(div)
    except Exception as e:
        print(e)
        print("{0} is not divisible by {1}".format(x,y))
    finally:
        print("{1} is divisible by {0}".format(x,y))

comp(5,0)

division by zero
5 is not divisible by 0
0 is divisible by 5


2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 
 
Output should come as below: 
 
Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket. 

In [1]:
subjects=["Americans ","Indians"]
verb = ["play","watch"]
objects=["Baseball","Cricket"]
output = [(x + " " + y + " " + z ) for x in subjects for y in verb for z in objects]
#print(i + " " + j + " " + k)

for i in output:
    print(i)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Task2

1. Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre               Theophile Vandermonde. 

In [2]:
import numpy as np 
  
input_vector = np.array([1, 2, 3, 4, 5]) 
  
output_matrix_inc = np.vander(input_vector,N=4, increasing = True) 
output_matrix_dec = np.vander(input_vector,N=6, increasing = False)   
print ("The ouput for the increasing boolean argument:")
print(output_matrix_inc)
print ("The ouput for the decreasing boolean argument::")
print(output_matrix_dec)

The ouput for the increasing boolean argument:
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
The ouput for the decreasing boolean argument::
[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]]
